### PR TITLE
Feature/board

### PR DESCRIPTION
**Pull request by laurarvegav**
We worked on the Board class, and did a rough draft for the initialize test and the expected return for a possible cells method.

### CODE REVIEW

**Comment by laurarvegav** [comment]
I got the cells method to pass the tests, also I'd like to see if you find okay the method, given that initialize is not needed.

**Comment by laurarvegav** [comment]
Together we drafted the test and code for the place_piece method for Board Class. Still not passing the test

**Comment by laurarvegav** [comment]
Together we finished the Board class Yay!

**Comment by laurarvegav** [comment]
Just noticed a typo, tests passing!

**Review by JRIV-10 — APPROVED** [review]
Good work on the create cells method to create the column and rows. I appreciate your patience struggling with me through the place piece method. All tests pass

**Pull request merged**
